import React from 'react';

const Icon: React.FC<React.HTMLProps<HTMLElement> & { faClass: string }> = ({ faClass, className, ...props }) => (
    <i {...props} className={`${faClass} ${className || ''}`} />
);

export const UserIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-user" />;
export const AssistantIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-comet" />;
export const SendIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-paper-plane" />;
export const PlusIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-plus" />;
export const MessageIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-message" />;
export const TrashIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-trash-can" />;
export const ChevronDownIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-chevron-down" />;
export const BrainIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-brain" />;
export const LoadingIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-spinner fa-spin" />;
export const SearchIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-magnifying-glass" />;
export const XIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-xmark" />;
export const CheckIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-check" />;
export const EditIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-pencil" />;
export const CopyIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-copy" />;
export const RegenerateIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-arrows-rotate" />;
export const AttachmentIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-paperclip" />;
export const CodeIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-code" />;
export const QuillIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-pen-fancy" />;
export const SarcasticIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-face-rolling-eyes" />;
export const ImageIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-image" />;
export const DownloadIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-download" />;
export const SettingsIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-sliders" />;
export const ToolIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-wrench" />;
export const BranchIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-code-branch" />;
export const SidebarIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-arrow-left-to-line" />;
export const GlobeIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-globe" />;
export const ChefIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-utensils" />;
export const BriefcaseIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-briefcase" />;
export const DumbbellIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-dumbbell" />;
export const PaletteIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-palette" />;
export const FilmIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-film" />;
export const GraduationCapIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-graduation-cap" />;
export const HeartIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-heart" />;
export const GavelIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-gavel" />;
export const TreeIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-tree" />;
export const MicrophoneIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-microphone" />;
export const ChartLineIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-chart-line" />;
export const CompassIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-compass" />;
export const FlaskIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-flask" />;
export const BookIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-book" />;
export const CommentsIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-comments" />;
export const KeyboardIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-keyboard" />;
export const SmileIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-regular fa-face-smile" />;
export const RocketIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-rocket" />;
export const ArrowLeftIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-arrow-left" />;
export const StarIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-star" />;
export const TagIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-tag" />;
export const FileLinesIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-file-lines" />;
export const CogIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-cog" />;
export const SunIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-sun" />;
export const MoonIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-moon" />;
export const DesktopIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-desktop" />;
export const UploadCloudIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-cloud-arrow-up" />;
export const DownloadCloudIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-cloud-arrow-down" />;
export const StopIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-stop" />;
export const BellIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-bell" />;
export const GoogleIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-brands fa-google" />;
export const OpenAIIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-comet" />;
export const AnthropicIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-a" />;
export const MetaIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-brands fa-meta" />;
export const MistralIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-wind" />;
export const GrokIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-x" />; // for xAI
export const GenericProviderIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-cube" />;
export const MuteIcon: React.FC<React.HTMLProps<HTMLElement>> = (props) => <Icon {...props} faClass="fa-solid fa-microphone-slash" />;